{
 "title": "Corezoid Erlang",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "label",
    "query": "capi,worker,mult,syncapi,limits,conf-agent-server"
   }
  ]
 },
 "panels": [
  {
   "title": "Erlang VM port limits",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "erlang_vm_port_count{tier=\"$label\"} / erlang_vm_port_limit{tier=\"$label\"} * 100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Erlang VM process limits",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "erlang_vm_process_count{tier=\"$label\"} / erlang_vm_process_limit{tier=\"$label\"} * 100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Erlang VM Schedulers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "erlang_vm_schedulers_online{tier=\"$label\"}/ erlang_vm_schedulers{tier=\"$label\"} * 100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Erlang VM threads",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "erlang_vm_threads{tier=\"$label\"} / erlang_vm_port_limit{tier=\"$label\"} * 100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "VM IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_bytes_output_total{tier=\"$label\"}[$interval])",
     "legendFormat": "Output Bytes-{{pod}}"
    },
    {
     "expr": "irate(erlang_vm_statistics_bytes_received_total{tier=\"$label\"}[$interval])",
     "legendFormat": "Received Bytes-{{pod}}"
    }
   ]
  },
  {
   "title": "VM Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_memory_system_bytes_total{tier=\"$label\", usage=\"atom\"}",
     "legendFormat": "Atoms-{{pod}}"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{tier=\"$label\", usage=\"binary\"}",
     "legendFormat": "Binary-{{pod}}"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{tier=\"$label\", usage=\"code\"}",
     "legendFormat": "Code-{{pod}}"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{tier=\"$label\", usage=\"ets\"}",
     "legendFormat": "ETS-{{pod}}"
    }
   ]
  },
  {
   "title": "Erlang VM process limits",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "erlang_vm_process_count{tier=\"$label\"} / erlang_vm_process_limit{tier=\"$label\"} * 100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Erlang VM atoms",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "erlang_vm_atom_count{tier=\"$label\"} / erlang_vm_atom_limit{tier=\"$label\"} * 100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "cce js compile errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 21, "x": 1, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cce_js_compile_error{tier=\"$label\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "lightCNode maps ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cce_light_cnode_map_ratio{tier=\"$label\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}