{
 "title": "Dundergitcall",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "owner_id",
    "label": "Owner",
    "query": "label_values(dundergitcall_usercode_duration_seconds_count, owner_id)"
   },
   {
    "name": "group_id",
    "label": "Group",
    "query": "label_values(dundergitcall_usercode_duration_seconds_count{owner_id=~\"$owner_id\"}, group_id)"
   },
   {
    "name": "service_id",
    "label": "Group",
    "query": "label_values(dundergitcall_usercode_duration_seconds_count{owner_id=~\"$owner_id\", group_id=~\"$group_id\"}, service_id)"
   }
  ]
 },
 "panels": [
  { "title": "dundergitcall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU used / limit % ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n\nmax(kube_pod_labels{label_tier=\"dundergitcall\",label_owner_id=~\"$owner_id\",label_group_id=~\"$group_id\",label_service_id=~\"$service_id\"})\nby (label_tier, pod)*on(pod)group_right(label_tier)\nlabel_replace\n(sum by(pod,container)\n(\nrate(container_cpu_usage_seconds_total{container=~\".*\",container!=\"POD\",container!=\"\",image!=\"\"}[2m])\n), \"pod\", \"$1\", \"pod_name\", \"(.+)\")\n\n) \n\n/\n\nsum(\n\nmax(kube_pod_labels{label_tier=\"dundergitcall\",label_owner_id=~\"$owner_id\",label_group_id=~\"$group_id\",label_service_id=~\"$service_id\"})\nby (label_tier, pod)*on(pod)group_right(label_tier)\nlabel_replace\n(\n\n(kube_pod_container_resource_limits_cpu_cores{}\n\n), \"pod\", \"$1\", \"pod\", \"(.+)\")\n\n)\n\n* 100"
    }
   ]
  },
  {
   "title": "Memory used \\ limit %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\nmax (kube_pod_labels{label_tier=~\"dundergitcall\",label_owner_id=~\"$owner_id\",label_group_id=~\"$group_id\",service_id=~\"$service_id\"}) by (label_tier, pod)\n    * \n    on(pod)\n    \n    group_right(label_tier)\n    \n    label_replace\n    \n    (avg by(pod,container)\n    \n      ( container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\"}\n    \n    ), \"pod\", \"$1\", \"pod_name\", \"(.+)\"\n  )\n)\n\n/ \n\nsum(\nmax (kube_pod_labels{label_tier=~\"dundergitcall\",label_owner_id=~\"$owner_id\",label_group_id=~\"$group_id\",service_id=~\"$service_id\"})\nby (label_tier, pod)*on(pod)group_right(label_tier)\nlabel_replace\n(\n\n(kube_pod_container_resource_limits_memory_bytes{}\n), \"pod\", \"$1\", \"pod\", \"(.+)\")\n)\n\n* 100\n"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"} * on(pod) group_left() max(kube_pod_labels{label_tier=\"dundergitcall\",label_owner_id=~\"$owner_id\",label_group_id=~\"$group_id\",label_service_id=~\"$service_id\"}) by (label_tier, label_owner_id, label_group_id, label_service_id, pod))"
    }
   ]
  },
  {
   "title": "Pending Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"} * on(pod) group_left() max(kube_pod_labels{label_tier=\"dundergitcall\",label_owner_id=~\"$owner_id\",label_group_id=~\"$group_id\",label_service_id=~\"$service_id\"}) by (label_tier, label_owner_id, label_group_id, label_service_id, pod))"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"} * on(pod) group_left() max(kube_pod_labels{label_tier=\"dundergitcall\",label_owner_id=~\"$owner_id\",label_group_id=~\"$group_id\",label_service_id=~\"$service_id\"}) by (label_tier, label_owner_id, label_group_id, label_service_id, pod))"
    }
   ]
  },
  {
   "title": "Unknown Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Unknown\"} * on(pod) group_left() max(kube_pod_labels{label_tier=\"dundergitcall\",label_owner_id=~\"$owner_id\",label_group_id=~\"$group_id\",label_service_id=~\"$service_id\"}) by (label_tier, label_owner_id, label_group_id, label_service_id, pod))"
    }
   ]
  },
  { "title": "usercode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU used / limit % ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n\nmax(kube_pod_labels{label_tier=\"dundergitcall-usercode\",label_owner_id=~\"$owner_id\",label_group_id=~\"$group_id\",label_service_id=~\"$service_id\"})\nby (label_tier, pod)*on(pod)group_right(label_tier)\nlabel_replace\n(sum by(pod,container)\n(\nrate(container_cpu_usage_seconds_total{container=~\".*\",container!=\"POD\",container!=\"\",image!=\"\"}[2m])\n), \"pod\", \"$1\", \"pod_name\", \"(.+)\")\n\n) \n\n/\n\nsum(\n\nmax(kube_pod_labels{label_tier=\"dundergitcall-usercode\",label_owner_id=~\"$owner_id\",label_group_id=~\"$group_id\",label_service_id=~\"$service_id\"})\nby (label_tier, pod)*on(pod)group_right(label_tier)\nlabel_replace\n(\n\n(kube_pod_container_resource_limits_cpu_cores{}\n\n), \"pod\", \"$1\", \"pod\", \"(.+)\")\n\n)\n\n* 100"
    }
   ]
  },
  {
   "title": "Memory used \\ limit %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\nmax (kube_pod_labels{label_tier=~\"dundergitcall-usercode\",label_owner_id=~\"$owner_id\",label_group_id=~\"$group_id\",service_id=~\"$service_id\"}) by (label_tier, pod)\n    * \n    on(pod)\n    \n    group_right(label_tier)\n    \n    label_replace\n    \n    (avg by(pod,container)\n    \n      ( container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\"}\n    \n    ), \"pod\", \"$1\", \"pod_name\", \"(.+)\"\n  )\n)\n\n/ \n\nsum(\nmax (kube_pod_labels{label_tier=~\"dundergitcall-usercode\",label_owner_id=~\"$owner_id\",label_group_id=~\"$group_id\",service_id=~\"$service_id\"})\nby (label_tier, pod)*on(pod)group_right(label_tier)\nlabel_replace\n(\n\n(kube_pod_container_resource_limits_memory_bytes{}\n), \"pod\", \"$1\", \"pod\", \"(.+)\")\n)\n\n* 100\n"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"} * on(pod) group_left() max(kube_pod_labels{label_tier=\"dundergitcall-usercode\",label_owner_id=~\"$owner_id\",label_group_id=~\"$group_id\",label_service_id=~\"$service_id\"}) by (label_tier, label_owner_id, label_group_id, label_service_id, pod))"
    }
   ]
  },
  {
   "title": "Pending Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"} * on(pod) group_left() max(kube_pod_labels{label_tier=\"dundergitcall-usercode\",label_owner_id=~\"$owner_id\",label_group_id=~\"$group_id\",label_service_id=~\"$service_id\"}) by (label_tier, label_owner_id, label_group_id, label_service_id, pod))"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"} * on(pod) group_left() max(kube_pod_labels{label_tier=\"dundergitcall-usercode\",label_owner_id=~\"$owner_id\",label_group_id=~\"$group_id\",label_service_id=~\"$service_id\"}) by (label_tier, label_owner_id, label_group_id, label_service_id, pod))"
    }
   ]
  },
  {
   "title": "Unknown Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Unknown\"} * on(pod) group_left() max(kube_pod_labels{label_tier=\"dundergitcall-usercode\",label_owner_id=~\"$owner_id\",label_group_id=~\"$group_id\",label_service_id=~\"$service_id\"}) by (label_tier, label_owner_id, label_group_id, label_service_id, pod))"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(dundergitcall_usercode_duration_seconds_count{owner_id=~\"$owner_id\",group_id=~\"$group_id\",service_id=~\"$service_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Seconds",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(dundergitcall_usercode_duration_seconds_sum{owner_id=~\"$owner_id\",group_id=~\"$group_id\",service_id=~\"$service_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Done, Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n   irate(dundergitcall_usercode_duration_seconds_count{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\", result=\"done\"}[5m])\n)"
    }
   ]
  },
  {
   "title": "Internal Errors, Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n   rate(dundergitcall_usercode_duration_seconds_count{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\",result=\"internal_error\"}[5m])\n)"
    }
   ]
  },
  {
   "title": "User Errors, Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n   rate(dundergitcall_usercode_duration_seconds_count{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\",result=\"error\"}[5m])\n)"
    }
   ]
  },
  {
   "title": "Task Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(dundergitcall_usercode_duration_seconds_bucket{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Task - Done , Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n   irate(dundergitcall_usercode_duration_seconds_count{owner_id=~\"$owner_id\",group_id=~\"$group_id\",service_id=~\"$service_id\",result=\"done\"}[10m])\n) by (owner_id,group_id,service_id)\n",
     "legendFormat": "done {{owner_id}}-{{group_id}}-{{service_id}}"
    }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Task Duration, Avg Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum  by (owner_id,group_id,service_id) (irate(dundergitcall_usercode_duration_seconds_sum{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\"}[2m]))\n/\n  sum  by (owner_id,group_id,service_id) (irate(dundergitcall_usercode_duration_seconds_count{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\"}[2m]))",
     "legendFormat": "{{owner-_id}}-{{group_id}}-{{service_id}}"
    }
   ]
  },
  {
   "title": "Wait Server, Avg Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (owner_id,group_id,service_id) (irate(dundergitcall_usercode_wait_duration_seconds_sum{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\"}[10m]))\n/\nsum by (owner_id,group_id,service_id) (irate(dundergitcall_usercode_wait_duration_seconds_count{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\"}[10m]))",
     "legendFormat": "instant {{owner_id}}-{{group_id}}-{{service_id}}"
    },
    {
     "expr": "sum by (owner_id,group_id,service_id) (rate(dundergitcall_usercode_wait_duration_seconds_sum{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\"}[5m]))\n/\nsum by (owner_id,group_id,service_id) (rate(dundergitcall_usercode_wait_duration_seconds_count{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\"}[5m]))",
     "legendFormat": "average {{owner_id}}-{{group_id}}-{{service_id}}"
    }
   ]
  },
  {
   "title": "Desired connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "# (active connections) - (avg duration * msg rate) = 0\n\n# duration\n( \n\n  (\n    sum  by (owner_id,group_id,service_id) (rate(dundergitcall_usercode_duration_seconds_sum{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\"}[10m]))\n    /\n    sum  by (owner_id,group_id,service_id) (rate(dundergitcall_usercode_duration_seconds_count{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\"}[10m]))\n  )\n  \n) * (\n# rate \n  sum(\n    irate(dundergitcall_usercode_duration_seconds_count{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\"}[10m])\n ) by (owner_id,group_id,service_id)\n)\n",
     "legendFormat": "{{owner_id}}-{{group_id}}-{{service_id}}"
    },
    {
     "expr": "# (active connections) - (avg duration * msg rate) = 0\n\n# duration\n( \n\n  (\n    sum  by (owner_id,group_id,service_id) (rate(dundergitcall_usercode_duration_seconds_sum{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\"}[10m]))\n    /\n    sum  by (owner_id,group_id,service_id) (rate(dundergitcall_usercode_duration_seconds_count{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\"}[10m]))\n  )\n  \n) * (\n# rate \n  sum(\n    irate(dundergitcall_usercode_duration_seconds_count{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\"}[10m])\n ) by (owner_id,group_id,service_id)\n)\n\n+\n\n(\n# wait time\n  sum by (owner_id,group_id,service_id) (rate(dundergitcall_usercode_wait_duration_seconds_sum{owner_id=~\"$owner_id\", group_id=~\"$group_id\", service_id=~\"$service_id\"}[5m]))\n  /\n  sum by (owner_id,group_id,service_id) (rate(dundergitcall_usercode_wait_duration_seconds_count{owner_id=~\"$owner_id\", group_id=~\"$group_id\", service_id=~\"$service_id\"}[5m]))\n)\n\n",
     "legendFormat": "+wait-{{owner_id}}-{{group_id}}-{{service_id}}"
    },
    {
     "expr": "# (active connections) - (avg duration * msg rate) = 0\n\n# duration\n( \n\n  (\n    sum  by (owner_id,group_id,service_id) (rate(dundergitcall_usercode_duration_seconds_sum{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\"}[10m]))\n    /\n    sum  by (owner_id,group_id,service_id) (rate(dundergitcall_usercode_duration_seconds_count{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\"}[10m]))\n  )\n  \n) * (\n# rate \n  sum(\n    irate(dundergitcall_usercode_duration_seconds_count{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\"}[10m])\n ) by (owner_id,group_id,service_id)\n)\n\n+\n2*\nlog10(1+\n(\n# wait time\n  sum by (owner_id,group_id,service_id) (rate(dundergitcall_usercode_wait_duration_seconds_sum{owner_id=~\"$owner_id\", group_id=~\"$group_id\", service_id=~\"$service_id\"}[5m]))\n  /\n  sum by (owner_id,group_id,service_id) (rate(dundergitcall_usercode_wait_duration_seconds_count{owner_id=~\"$owner_id\", group_id=~\"$group_id\", service_id=~\"$service_id\"}[5m]))\n)\n)\n\n",
     "legendFormat": "+2log(1+wait)-{{owner_id}}-{{group_id}}-{{service_id}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (owner_id,group_id,service_id)(dundergitcall_usercode_active_connections{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\"})",
     "legendFormat": "{{owner_id}}-{{group_id}}-{{service_id}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Tasks - Internal Error , Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "legendFormat": "{{owner_id}}-{{group_id}}" },
    {
     "expr": "sum(\n   irate(dundergitcall_usercode_duration_seconds_count{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\",result=\"internal_error\"}[5m])\n) by (owner_id,group_id,service_id)\n",
     "legendFormat": "{{owner_id}}-{{group_id}}-{{service_id}}"
    }
   ]
  },
  {
   "title": "Retries , Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n   irate(dundergitcall_usercode_retry_count{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\"}[5m])\n) by (owner_id,group_id,service_id)",
     "legendFormat": "{{owner_id}}-{{group_id}}-{{service_id}}"
    }
   ]
  },
  {
   "title": "Tasks - User Errors , Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n   irate(dundergitcall_usercode_duration_seconds_count{owner_id=~\"$owner_id\", group_id=~\"$group_id\",service_id=~\"$service_id\",result=\"error\"}[5m])\n) by (owner_id,group_id,service_id)\n",
     "legendFormat": "{{owner_id}}-{{group_id}}-{{service_id}}"
    }
   ]
  }
 ]
}