{
 "title": "GitCall",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Status Update", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status Update Duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(consumer_consume_duration_seconds_bucket{tier=\"gitcall\",consumer=\"dundergitcall_status_update\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Status Update, Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(consumer_consume_duration_seconds_count{tier=\"gitcall\",consumer=\"dundergitcall_status_update\"}[5m]))"
    }
   ]
  },
  {
   "title": "Run Service Duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(consumer_consume_duration_seconds_bucket{tier=\"gitcall\",consumer=\"run_dundergitcall_service\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Run Service, Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(consumer_consume_duration_seconds_count{tier=\"gitcall\",consumer=\"run_dundergitcall_service\"}[5m]))"
    },
    {
     "expr": "sum by (instance) (rate(consumer_consume_duration_seconds_count{tier=\"gitcall\",consumer=\"run_dundergitcall_service\"}[30m]))"
    }
   ]
  },
  {
   "title": "Build Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Build Service, Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (rate(consumer_consume_duration_seconds_count{tier=\"gitcall\",consumer=\"build_dundergitcall_service\"}[5m]))"
      }
     ]
    },
    {
     "title": "Build Service, Avg LOG2 Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short", "label": "Sec" }
     ],
     "targets": [
      {
       "expr": "  sum by (instance) (rate(consumer_consume_duration_seconds_sum{tier=\"gitcall\",consumer=\"build_dundergitcall_service\"}[5m]))\n/\n  sum by (instance) (rate(consumer_consume_duration_seconds_count{tier=\"gitcall\",consumer=\"build_dundergitcall_service\"}[5m]))"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "Deploy Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deploy Service, Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(consumer_consume_duration_seconds_count{tier=\"gitcall\",consumer=\"deploy_dundergitcall_service\"}[2m])) by (instance)"
      }
     ]
    },
    {
     "title": "Deploy Service, Avg LOG2 Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short", "label": "Sec" }
     ],
     "targets": [
      {
       "expr": "  sum by (instance) (rate(consumer_consume_duration_seconds_sum{tier=\"gitcall\",consumer=\"deploy_dundergitcall_service\"}[5m]))\n/\n  sum by (instance) (rate(consumer_consume_duration_seconds_count{tier=\"gitcall\",consumer=\"deploy_dundergitcall_service\"}[5m]))"
      },
      {
       "expr": "sum by (instance) (consumer_consume_expire_seconds{tier=\"gitcall\",consumer=\"deploy_dundergitcall_service\"})"
      }
     ]
    }
   ]
  },
  { "title": "Run Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  { "title": "Get Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Get Service Duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(consumer_consume_duration_seconds_bucket{tier=\"gitcall\",consumer=\"get_dundergitcall_service\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get Service, Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(consumer_consume_duration_seconds_count{tier=\"gitcall\",consumer=\"get_dundergitcall_service\"}[5m]))"
    },
    {
     "expr": "sum by (instance) (rate(consumer_consume_duration_seconds_count{tier=\"gitcall\",consumer=\"get_dundergitcall_service\"}[30m]))"
    }
   ]
  },
  { "title": "Save Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Save Service, Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(consumer_consume_duration_seconds_count{tier=\"gitcall\",consumer=\"save_dundergitcall_service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Save Service, Avg LOG2 Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "Sec" }
   ],
   "targets": [
    {
     "expr": "  sum by (instance) (rate(consumer_consume_duration_seconds_sum{tier=\"gitcall\",consumer=\"save_dundergitcall_service\"}[5m]))\n/\n  sum by (instance) (rate(consumer_consume_duration_seconds_count{tier=\"gitcall\",consumer=\"save_dundergitcall_service\"}[5m]))"
    },
    {
     "expr": "sum by (instance) (consumer_consume_expire_seconds{tier=\"gitcall\",consumer=\"save_dundergitcall_service\"})"
    }
   ]
  },
  { "title": "Validate Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Validate Service, Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(consumer_consume_duration_seconds_count{tier=\"gitcall\",consumer=\"validate_dundergitcall_service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Validate Service, Avg LOG2 Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short", "label": "Sec" }
   ],
   "targets": [
    {
     "expr": "  sum by (instance) (rate(consumer_consume_duration_seconds_sum{tier=\"gitcall\",consumer=\"validate_dundergitcall_service\"}[5m]))\n/\n  sum by (instance) (rate(consumer_consume_duration_seconds_count{tier=\"gitcall\",consumer=\"validate_dundergitcall_service\"}[5m]))"
    },
    {
     "expr": "sum by (instance) (consumer_consume_expire_seconds{tier=\"gitcall\",consumer=\"validate_dundergitcall_service\"})"
    }
   ]
  },
  { "title": "Stop Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Stop Service, Avg LOG2 Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short", "label": "Sec" }
   ],
   "targets": [
    {
     "expr": "  sum by (instance) (rate(consumer_consume_duration_seconds_sum{tier=\"gitcall\",consumer=\"stop_dundergitcall_service\"}[5m]))\n/\n  sum by (instance) (rate(consumer_consume_duration_seconds_count{tier=\"gitcall\",consumer=\"stop_dundergitcall_service\"}[5m]))"
    },
    {
     "expr": "sum by (instance) (consumer_consume_expire_seconds{tier=\"gitcall\",consumer=\"stop_dundergitcall_service\"})"
    }
   ]
  },
  {
   "title": "Stop Service, Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(consumer_consume_duration_seconds_count{tier=\"gitcall\",consumer=\"stop_dundergitcall_service\"}[5m]))"
    }
   ]
  },
  { "title": "Go", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Total Alloc, Bytes ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    rate(go_memstats_alloc_bytes_total{tier=\"gitcall\"}[2m])\n) by (instance)"
    }
   ]
  },
  {
   "title": "GC, Avg Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(go_gc_duration_seconds_sum{tier=\"gitcall\"}[2m])\n) by (instance)\n/ \nsum(\n  rate(go_gc_duration_seconds_count{tier=\"gitcall\"}[2m])\n) by (instance)"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{tier=\"gitcall\"}) by (instance)"
    }
   ]
  }
 ]
}