{
 "title": "Pimp",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Apply, Done",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(pimp_service_apply_duration_seconds_count{result=\"done\"}[5m])"
    }
   ]
  },
  {
   "title": "Apply, Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(pimp_service_apply_duration_seconds_count{result=\"error\"}[5m])"
    }
   ]
  },
  {
   "title": "Delete, Done",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(pimp_service_delete_duration_seconds_count{result=\"done\"}[5m])"
    }
   ]
  },
  {
   "title": "Delete, Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(pimp_service_delete_duration_seconds_count{result=\"done\"}[5m])"
    }
   ]
  },
  {
   "title": "Modify queue size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(pimp_service_modify_queue_size[5m]))"
    }
   ]
  },
  {
   "title": "Apply requests",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(pimp_service_apply_duration_seconds_bucket[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Apply requests, rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pimp_service_apply_duration_seconds_count{result=\"done\"}[5m])",
     "legendFormat": "done"
    },
    {
     "expr": "irate(pimp_service_apply_duration_seconds_count{result=\"error\"}[5m])",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Delete requests",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(pimp_service_delete_duration_seconds_bucket[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Delete requests, rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pimp_service_delete_duration_seconds_count{result=\"done\"}[5m])",
     "legendFormat": "done"
    },
    {
     "expr": "irate(pimp_service_delete_duration_seconds_count{result=\"error\"}[5m])",
     "legendFormat": "error"
    }
   ]
  }
 ]
}