{
 "title": "SyncAPI",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Create task, rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(syncapi_create_task_duration_seconds_count{status=\"done\",kubernetes_namespace=\"$namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(max(kube_pod_labels{label_tier=~\"syncapi\"})\nby (label_tier, pod)*on(pod)group_right(label_tier)\nlabel_replace\n(sum by(pod,container)\n(\nrate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=~\".*\",container!=\"POD\",container!=\"\",image!=\"\"}[2m])\n), \"pod\", \"$1\", \"pod_name\", \"(.+)\"))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "   sum( max (kube_pod_labels{label_tier=~\"syncapi\"}) by (label_tier, pod)\n    * \n    on(pod)\n    \n    group_right(label_tier)\n    \n    label_replace\n    \n    (avg by(pod,container)\n    \n      ( container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"POD\",container!=\"\",image!=\"\"}\n    \n    ), \"pod\", \"$1\", \"pod_name\", \"(.+)\"\n  ))\n"
    }
   ]
  },
  {
   "title": "Log, errors rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate( ({tier=\"syncapi\",namespace=\"$namespace\"} |= \"[error]\")[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Auth task, errors rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(syncapi_auth_task_count{status=\"error\",kubernetes_namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Create tasks, errors rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(syncapi_create_task_duration_seconds_count{status=\"error\",kubernetes_namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Proxy callback, errors rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(syncapi_proxy_callback_duration_seconds_count{status=\"error\",kubernetes_namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Wait callback, errors rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(syncapi_wait_callback_duration_seconds_count{status=\"error\",kubernetes_namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "create task done rate",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(syncapi_create_task_duration_seconds_count{status=\"done\",kubernetes_namespace=\"$namespace\"}[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kube_pod_labels{label_tier=~\"syncapi\"})\nby (label_tier, pod)*on(pod)group_right(label_tier)\nlabel_replace\n(sum by(pod,container)\n(\nrate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=~\".*\",container!=\"POD\",container!=\"\",image!=\"\"}[2m])\n), \"pod\", \"$1\", \"pod_name\", \"(.+)\")",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "    max (kube_pod_labels{label_tier=~\"syncapi\"}) by (label_tier, pod)\n    * \n    on(pod)\n    \n    group_right(label_tier)\n    \n    label_replace\n    \n    (avg by(pod,container)\n    \n      ( container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"POD\",container!=\"\",image!=\"\"}\n    \n    ), \"pod\", \"$1\", \"pod_name\", \"(.+)\"\n  )\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Errors, rate",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(syncapi_auth_task_count{status=\"error\",kubernetes_namespace=\"$namespace\"}[5m])",
     "legendFormat": "auth task"
    },
    {
     "expr": "rate(syncapi_create_task_duration_seconds_count{status=\"error\",kubernetes_namespace=\"$namespace\"}[5m])",
     "legendFormat": "create task"
    },
    {
     "expr": "rate(syncapi_wait_callback_duration_seconds_count{status=\"error\",kubernetes_namespace=\"$namespace\"}[5m])",
     "legendFormat": "wait callback"
    },
    {
     "expr": "rate(syncapi_proxy_callback_duration_seconds_count{status=\"error\",kubernetes_namespace=\"$namespace\"}[5m])",
     "legendFormat": "proxy callback"
    }
   ]
  },
  { "title": "Durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Proxy duration",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "sum(irate(syncapi_proxy_callback_duration_seconds_bucket{status=\"done\",kubernetes_namespace=\"$namespace\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Create task duration",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "sum(irate(syncapi_create_task_duration_seconds_bucket{status=\"done\",kubernetes_namespace=\"$namespace\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Wait callback, all duration",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "sum(irate(syncapi_wait_callback_duration_seconds_bucket{kubernetes_namespace=\"$namespace\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    },
    { "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Proxy callback rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "collapsed": true,
   "panels": [
    {
     "title": "proxy callback rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(syncapi_proxy_callback_duration_seconds_count{status=\"done\",kubernetes_namespace=\"$namespace\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}